# Site settings
title: Radiologie Helfer
description: A website with a hacker-style background

# Theme settings
theme: jekyll-theme-hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed

# URL settings
url: "https://sadritmora.github.io"
baseurl: ""

# Author settings
author:
  name: SadritMora
  email: oanapanainte1@yahoo.com

# Sitemap settings
sitemap:
  changefreq: daily
  priority: 1.0

# Feed settings
feed:
  path: feed.xml

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include additional files
include:
  - _pages

# Defaults for Front Matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "<Your Name>"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "<Your Name>"




