title: default theme...
email: email@example.com
description: ...description...
url: "https://sadritmora.github.io/"

# Build settings
theme: jekyll-theme-hacker

remote_theme: pages-themes/hacker@v0.2.0
